/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.android.based.app.View;

import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import pos.android.based.app.View.ProductForm;

/**
 *
 * @author Asus
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    private String loggedInUsername;
    private String userRole;

    public MainUI(String username, String role) {
        this.loggedInUsername = username;
        this.userRole = role;
        initComponents();
        
        ManageBtn.setVisible("admin".equalsIgnoreCase(userRole));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeBtnGroup = new javax.swing.ButtonGroup();
        homepagePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JToggleButton();
        productsBtn = new javax.swing.JToggleButton();
        TransactionsBtn = new javax.swing.JToggleButton();
        usersBtn = new javax.swing.JToggleButton();
        ManageBtn = new javax.swing.JToggleButton();
        logoutBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        homepagePanel.setBackground(new java.awt.Color(0, 0, 0));
        homepagePanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        homepagePanel.setPreferredSize(new java.awt.Dimension(660, 560));
        homepagePanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 193, 217));
        jLabel1.setText("SETUJU POS");
        homepagePanel.add(jLabel1);
        jLabel1.setBounds(40, 30, 220, 58);

        homeBtn.setBackground(new java.awt.Color(70, 73, 75));
        homeBtnGroup.add(homeBtn);
        homeBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(251, 193, 217));
        homeBtn.setText("Home");
        homeBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        homeBtn.setPreferredSize(new java.awt.Dimension(100, 70));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        homepagePanel.add(homeBtn);
        homeBtn.setBounds(80, 180, 130, 90);

        productsBtn.setBackground(new java.awt.Color(51, 51, 51));
        homeBtnGroup.add(productsBtn);
        productsBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        productsBtn.setForeground(new java.awt.Color(251, 193, 217));
        productsBtn.setText("Products");
        productsBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        productsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productsBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        productsBtn.setPreferredSize(new java.awt.Dimension(100, 70));
        productsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsBtnActionPerformed(evt);
            }
        });
        homepagePanel.add(productsBtn);
        productsBtn.setBounds(260, 180, 130, 90);

        TransactionsBtn.setBackground(new java.awt.Color(51, 51, 51));
        homeBtnGroup.add(TransactionsBtn);
        TransactionsBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        TransactionsBtn.setForeground(new java.awt.Color(251, 193, 217));
        TransactionsBtn.setText("Transactions");
        TransactionsBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TransactionsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TransactionsBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        TransactionsBtn.setPreferredSize(new java.awt.Dimension(100, 70));
        TransactionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionsBtnActionPerformed(evt);
            }
        });
        homepagePanel.add(TransactionsBtn);
        TransactionsBtn.setBounds(440, 180, 130, 90);

        usersBtn.setBackground(new java.awt.Color(51, 51, 51));
        homeBtnGroup.add(usersBtn);
        usersBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        usersBtn.setForeground(new java.awt.Color(251, 193, 217));
        usersBtn.setText("Users");
        usersBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        usersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usersBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        usersBtn.setPreferredSize(new java.awt.Dimension(100, 70));
        usersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersBtnActionPerformed(evt);
            }
        });
        homepagePanel.add(usersBtn);
        usersBtn.setBounds(260, 310, 130, 90);

        ManageBtn.setBackground(new java.awt.Color(51, 51, 51));
        homeBtnGroup.add(ManageBtn);
        ManageBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ManageBtn.setForeground(new java.awt.Color(251, 193, 217));
        ManageBtn.setText("Manage User");
        ManageBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ManageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        ManageBtn.setPreferredSize(new java.awt.Dimension(100, 70));
        ManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageBtnActionPerformed(evt);
            }
        });
        homepagePanel.add(ManageBtn);
        ManageBtn.setBounds(80, 310, 130, 90);

        logoutBtn.setBackground(new java.awt.Color(111, 29, 29));
        homeBtnGroup.add(logoutBtn);
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        logoutBtn.setPreferredSize(new java.awt.Dimension(100, 70));
        homepagePanel.add(logoutBtn);
        logoutBtn.setBounds(440, 310, 130, 90);

        getContentPane().add(homepagePanel);
        homepagePanel.setBounds(0, 0, 660, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsBtnActionPerformed
        // TODO add your handling code here:
        try {
            ProductForm pd = new ProductForm(loggedInUsername, userRole);
            pd.setVisible(true);
            pd.pack();
            pd.setLocationRelativeTo(null);
            pd.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE); // Supaya tidak tutup aplikasi utama
            } catch (MalformedURLException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, "Gagal membuka ProductForm", ex);
        }
    }//GEN-LAST:event_productsBtnActionPerformed

    private void TransactionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransactionsBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBtnActionPerformed

    private void usersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersBtnActionPerformed
        // TODO add your handling code here:
        UserForm us = new UserForm(loggedInUsername);
        us.setVisible(true);
        us.pack();
        us.setLocationRelativeTo(null);
        us.setDefaultCloseOperation(ProductForm.EXIT_ON_CLOSE);
    }//GEN-LAST:event_usersBtnActionPerformed

    private void ManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageBtnActionPerformed
        // TODO add your handling code here:
        ManageUserForm mu = new ManageUserForm();
        mu.setVisible(true);
        mu.pack();
        mu.setLocationRelativeTo(null);
        mu.setDefaultCloseOperation(ProductForm.EXIT_ON_CLOSE);
    }//GEN-LAST:event_ManageBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainUI("demoUser", "admin").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ManageBtn;
    private javax.swing.JToggleButton TransactionsBtn;
    private javax.swing.JToggleButton homeBtn;
    private javax.swing.ButtonGroup homeBtnGroup;
    private javax.swing.JPanel homepagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton logoutBtn;
    private javax.swing.JToggleButton productsBtn;
    private javax.swing.JToggleButton usersBtn;
    // End of variables declaration//GEN-END:variables
}
