/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.android.based.app.View;
import pos.android.based.app.ProductForm;
/**
 *
 * @author Asus
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeBtnGroup = new javax.swing.ButtonGroup();
        homepagePanel = new javax.swing.JPanel();
        sidebarContainer = new javax.swing.JPanel();
        homeBtn = new javax.swing.JToggleButton();
        productsBtn = new javax.swing.JToggleButton();
        TransactionsBtn = new javax.swing.JToggleButton();
        usersBtn = new javax.swing.JToggleButton();
        logsBtn = new javax.swing.JToggleButton();
        logoutBtn = new javax.swing.JToggleButton();
        dashboardPanel = new javax.swing.JPanel();
        paneldb1 = new javax.swing.JPanel();
        paneldb2 = new javax.swing.JPanel();
        paneldb3 = new javax.swing.JPanel();
        paneldb4 = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        homepagePanel.setBackground(new java.awt.Color(0, 0, 0));
        homepagePanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        homepagePanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        homepagePanel.setLayout(null);

        sidebarContainer.setBackground(new java.awt.Color(0, 0, 0));

        homeBtn.setBackground(new java.awt.Color(251, 193, 217));
        homeBtnGroup.add(homeBtn);
        homeBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(51, 51, 51));
        homeBtn.setText("Home");
        homeBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        homeBtn.setPreferredSize(new java.awt.Dimension(100, 70));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        sidebarContainer.add(homeBtn);

        productsBtn.setBackground(new java.awt.Color(51, 51, 51));
        homeBtnGroup.add(productsBtn);
        productsBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        productsBtn.setForeground(new java.awt.Color(251, 193, 217));
        productsBtn.setText("Products");
        productsBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        productsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productsBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        productsBtn.setPreferredSize(new java.awt.Dimension(100, 70));
        productsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsBtnActionPerformed(evt);
            }
        });
        sidebarContainer.add(productsBtn);

        TransactionsBtn.setBackground(new java.awt.Color(51, 51, 51));
        homeBtnGroup.add(TransactionsBtn);
        TransactionsBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        TransactionsBtn.setForeground(new java.awt.Color(251, 193, 217));
        TransactionsBtn.setText("Transactions");
        TransactionsBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TransactionsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TransactionsBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        TransactionsBtn.setPreferredSize(new java.awt.Dimension(100, 70));
        TransactionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionsBtnActionPerformed(evt);
            }
        });
        sidebarContainer.add(TransactionsBtn);

        usersBtn.setBackground(new java.awt.Color(51, 51, 51));
        homeBtnGroup.add(usersBtn);
        usersBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        usersBtn.setForeground(new java.awt.Color(251, 193, 217));
        usersBtn.setText("Users");
        usersBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        usersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usersBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        usersBtn.setPreferredSize(new java.awt.Dimension(100, 70));
        sidebarContainer.add(usersBtn);

        logsBtn.setBackground(new java.awt.Color(51, 51, 51));
        homeBtnGroup.add(logsBtn);
        logsBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        logsBtn.setForeground(new java.awt.Color(251, 193, 217));
        logsBtn.setText("Logs");
        logsBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logsBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        logsBtn.setPreferredSize(new java.awt.Dimension(100, 70));
        sidebarContainer.add(logsBtn);

        logoutBtn.setBackground(new java.awt.Color(51, 51, 51));
        homeBtnGroup.add(logoutBtn);
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(251, 193, 217));
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        logoutBtn.setPreferredSize(new java.awt.Dimension(100, 70));
        sidebarContainer.add(logoutBtn);

        homepagePanel.add(sidebarContainer);
        sidebarContainer.setBounds(60, 110, 130, 460);

        dashboardPanel.setBackground(new java.awt.Color(0, 0, 0));
        dashboardPanel.setPreferredSize(new java.awt.Dimension(72, 72));

        paneldb1.setBackground(new java.awt.Color(51, 51, 51));
        paneldb1.setForeground(new java.awt.Color(250, 250, 250));
        paneldb1.setPreferredSize(new java.awt.Dimension(400, 150));

        javax.swing.GroupLayout paneldb1Layout = new javax.swing.GroupLayout(paneldb1);
        paneldb1.setLayout(paneldb1Layout);
        paneldb1Layout.setHorizontalGroup(
            paneldb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        paneldb1Layout.setVerticalGroup(
            paneldb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        dashboardPanel.add(paneldb1);

        paneldb2.setBackground(new java.awt.Color(51, 51, 51));
        paneldb2.setForeground(new java.awt.Color(250, 250, 250));
        paneldb2.setPreferredSize(new java.awt.Dimension(400, 150));

        javax.swing.GroupLayout paneldb2Layout = new javax.swing.GroupLayout(paneldb2);
        paneldb2.setLayout(paneldb2Layout);
        paneldb2Layout.setHorizontalGroup(
            paneldb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        paneldb2Layout.setVerticalGroup(
            paneldb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        dashboardPanel.add(paneldb2);

        paneldb3.setBackground(new java.awt.Color(51, 51, 51));
        paneldb3.setForeground(new java.awt.Color(250, 250, 250));
        paneldb3.setPreferredSize(new java.awt.Dimension(400, 150));

        javax.swing.GroupLayout paneldb3Layout = new javax.swing.GroupLayout(paneldb3);
        paneldb3.setLayout(paneldb3Layout);
        paneldb3Layout.setHorizontalGroup(
            paneldb3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        paneldb3Layout.setVerticalGroup(
            paneldb3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        dashboardPanel.add(paneldb3);

        paneldb4.setBackground(new java.awt.Color(51, 51, 51));
        paneldb4.setForeground(new java.awt.Color(250, 250, 250));
        paneldb4.setPreferredSize(new java.awt.Dimension(400, 150));

        javax.swing.GroupLayout paneldb4Layout = new javax.swing.GroupLayout(paneldb4);
        paneldb4.setLayout(paneldb4Layout);
        paneldb4Layout.setHorizontalGroup(
            paneldb4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        paneldb4Layout.setVerticalGroup(
            paneldb4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        dashboardPanel.add(paneldb4);

        homepagePanel.add(dashboardPanel);
        dashboardPanel.setBounds(180, 40, 530, 670);

        logoPanel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Onyx", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 193, 217));
        jLabel1.setText("SETUJU POS");

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        homepagePanel.add(logoPanel);
        logoPanel.setBounds(60, 10, 120, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(homepagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homepagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsBtnActionPerformed
        // TODO add your handling code here:
        ProductForm pd = new ProductForm();
        pd.setVisible(true);
        pd.pack();
        pd.setLocationRelativeTo(null);
        pd.setDefaultCloseOperation(ProductForm.EXIT_ON_CLOSE);
    }//GEN-LAST:event_productsBtnActionPerformed

    private void TransactionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransactionsBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton TransactionsBtn;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JToggleButton homeBtn;
    private javax.swing.ButtonGroup homeBtnGroup;
    private javax.swing.JPanel homepagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JToggleButton logoutBtn;
    private javax.swing.JToggleButton logsBtn;
    private javax.swing.JPanel paneldb1;
    private javax.swing.JPanel paneldb2;
    private javax.swing.JPanel paneldb3;
    private javax.swing.JPanel paneldb4;
    private javax.swing.JToggleButton productsBtn;
    private javax.swing.JPanel sidebarContainer;
    private javax.swing.JToggleButton usersBtn;
    // End of variables declaration//GEN-END:variables
}
